AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  quiz application to create and take quizes

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  QuizQuestionsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: quiz_questions/
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        AllQuestions:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /questions
            Method: get
        QuestionById:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /questions/{id}
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  QuizQuestionsFunction:
    Description: "Quiz Questions Lambda Function ARN"
    Value: !GetAtt QuizQuestionsFunction.Arn
  QuizQuestionsFunctionIamRole:
    Description: "Implicit IAM Role created for Quiz Questions function"
    Value: !GetAtt QuizQuestionsFunctionRole.Arn
  QuizQuestionsApi:
    Description: "API Gateway endpoint URL for Prod stage for Quiz Questions function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/questions"
